server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: fegin-drus
  mongodb:
    uri: mongodb://name:password@localhost:27017/test
