server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: fegin-drus
#此为spring cloud配置文件格式
redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password:
  timeout: 500
  pool:
    max-active: 20 # 连接池最大连接数（使用负值表示没有限制
    max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制
    max-idle: 8      # 连接池中的最大空闲连接
    min-idle: 0       # 连接池中的最小空闲连接
