server:
  port: 8201
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: web-medicalhomepage-server
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.101.109:3306/yiyao?characterEncoding=utf-8
    username: root
    password: root

    thymeleaf:
      encoding: UTF-8
      servlet:
        content-type: text/html

mybatis:
  mapper-locations: classpath:mapper/*.xml


