server:
  port: 8062
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: qhp-feign

    thymeleaf:
      encoding: UTF-8
      servlet:
        content-type: text/html

